name: fellow4u_ui
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


# State Management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^6.1.0
  web_socket_channel: ^3.0.1
  internet_connection_checker: ^1.0.0+1
  get_it: ^8.0.2
  go_router: ^14.6.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication
  # firebase_auth: ^5.3.3
  # google_sign_in: ^6.2.1

  # Analytics & Crash Reporting
  # firebase_core: ^3.8.0
  # firebase_analytics: ^11.3.5
  # firebase_crashlytics: ^4.1.5

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.15
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  intl: any
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  image_picker: ^1.0.5
  flutter_map: ^7.0.2
  geolocator: ^13.0.2

  # Push Notifications
  # firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1

  # Payments
  flutter_stripe: ^11.3.0
  in_app_purchase: ^3.1.11

  # Utils
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.14.1
  share_plus: ^10.1.2
  path_provider: ^2.1.1
  package_info_plus: ^8.1.1
  device_info_plus: ^11.1.1
  permission_handler: ^11.1.0
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  uuid: ^4.2.2

  # Testing
  mocktail: ^1.0.1
  fake_async: ^1.3.1
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.7
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Development Tools  
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  flutter_gen_runner: ^5.3.2

  # Testing
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "assets/logo/fellow4u_logo.png"
  adaptive_icon_foreground: "assets/logo/fellow4u_logo.png"
  image_path: "assets/logo/fellow4u_logo.png"
  icon_size: 48
  adaptive_icon_gravity: center
  adaptive_icon_foreground_color: "#FFFFFF"
  adaptive_icon_background_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/logo/fellow4u_logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Splash Screen Assets
    - assets/splash_images/cloud_bottom_right.png
    - assets/splash_images/cloud_left.png
    - assets/splash_images/cloud_top_right.png
    - assets/splash_images/fellow4u_logo.png
    - assets/splash_images/ground.png
    - assets/splash_images/hat.png
    - assets/splash_images/plane.png
    - assets/splash_images/tail_plane.png
    - assets/splash_images/tree_left1.png
    - assets/splash_images/tree_left2.png
    - assets/splash_images/tree_over_right.png

    # Icons
    - assets/icons/Facebook.png
    - assets/icons/Line.png
    - assets/icons/Talk.png
    

    # Images
    - assets/images/header_background.png
    - assets/images/autumn_background.png
    - assets/images/travel_background.png
    
    
    - assets/logo/fellow4u_logo.png
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg
    - .env

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.ttf
        - asset: fonts/SF-Pro-Display-RegularItalic.ttf
        - asset: fonts/SF-Pro-Display-Black.ttf
        - asset: fonts/SF-Pro-Display-BlackItalic.ttf
        - asset: fonts/SF-Pro-Display-Bold.ttf
        - asset: fonts/SF-Pro-Display-BoldItalic.ttf
        - asset: fonts/SF-Pro-Display-Light.ttf
        - asset: fonts/SF-Pro-Display-LightItalic.ttf
        - asset: fonts/SF-Pro-Display-Medium.ttf
        - asset: fonts/SF-Pro-Display-MediumItalic.ttf
        - asset: fonts/SF-Pro-Display-Semibold.ttf
        - asset: fonts/SF-Pro-Display-SemiboldItalic.ttf
        - asset: fonts/SF-Pro-Display-Thin.ttf
        - asset: fonts/SF-Pro-Display-ThinItalic.ttf
        - asset: fonts/SF-Pro-Display-Ultralight.ttf
        - asset: fonts/SF-Pro-Display-UltralightItalic.ttf

